import { supabase } from './supabaseClient'

/**
 * Get or create a unique session ID for anonymous user
 * Stored in localStorage for persistence
 */
function getSessionId(): string {
  const storageKey = 'jiyi_session_id'
  let sessionId = localStorage.getItem(storageKey)
  
  if (!sessionId) {
    // Generate a unique session ID based on timestamp and random string
    sessionId = `session_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`
    localStorage.setItem(storageKey, sessionId)
  }
  
  return sessionId
}

/**
 * Sync anonymous user to database using upsert
 * Creates or updates the nickname in anonymous_users table
 */
export async function syncAnonymousUser(nickname: string): Promise<void> {
  const sessionId = getSessionId()
  
  if (!nickname || nickname.trim().length === 0) {
    console.warn('Nickname cannot be empty')
    return
  }

  const { error } = await supabase
    .from('anonymous_users')
    .upsert(
      { 
        session_id: sessionId, 
        nickname: nickname.trim()
      },
      { 
        onConflict: 'session_id'
      }
    )
  
  if (error) {
    console.error('Failed to sync anonymous user:', error.message)
    throw error
  }
}

/**
 * Send a message to the chat
 * First ensures the anonymous user is synced, then inserts the message
 */
export async function sendMessage(content: string, nickname: string): Promise<boolean> {
  // Ensure user identity is synced first
  await syncAnonymousUser(nickname)
  
  const sessionId = getSessionId()
  
  if (!content || content.trim().length === 0) {
    console.warn('Message content cannot be empty')
    return false
  }

  const { error } = await supabase
    .from('messages')
    .insert([
      {
        session_id: sessionId,
        content: content.trim()
        // id and created_at are auto-generated by the database
      }
    ])

  if (error) {
    console.error('Failed to send message:', error.message)
    return false
  }

  return true
}

/**
 * Fetch chat history with user nicknames joined from anonymous_users table
 * Returns formatted array of messages with nickname
 */
export async function fetchChatHistory(): Promise<ChatMessage[]> {
  const { data, error } = await supabase
    .from('messages')
    .select(`
      id,
      content,
      created_at,
      session_id,
      anonymous_users (
        nickname
      )
    `)
    .order('created_at', { ascending: true })

  if (error) {
    console.error('Failed to fetch chat history:', error.message)
    return []
  }

  // Format the data for easier frontend binding
  return data.map((msg: any) => ({
    id: msg.id,
    content: msg.content,
    createdAt: msg.created_at,
    sessionId: msg.session_id,
    // Provide a fallback nickname if user data is missing
    nickname: msg.anonymous_users?.nickname || '未知路人'
  }))
}

export interface ChatMessage {
  id: string
  content: string
  createdAt: string
  sessionId: string
  nickname: string
}
